cache:
  apt: true
  directories:
    - $HOME/.cache/pip
language: python
notifications:
  email: false
python:
  - 2.7
#  - 3.4  temporarily inactive (problem with travis) 
  - 3.6
sudo: false
before_install:
  - sudo apt-get install python-tk
  - sudo apt-get install python3-tk
script:
  - python setup.py test
