cache:
  apt: true
  directories:
    - $HOME/.cache/pip
language: python
notifications:
  email: false
python:
  - 2.7
  - "3.4_with_system_site_packages"
  - 3.6
virtualenv:
  system_site_packages: true
sudo: false
before_install:
  - sudo apt-get install python-tk
  - sudo apt-get install python3-tk
script:
  - python setup.py test
