cache:
  apt: true
  directories:
    - $HOME/.cache/pip
language: python
notifications:
  email: false
python:
  - 2.7
  - 3.4
sudo: false
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-tk
script:
  - python setup.py test