cache:
  apt: true
  directories:
    - $HOME/.cache/pip
language: python
notifications:
  email: false
python:
  - 3.6
  - 3.7
sudo: false
before_install:
  - sudo apt-get install python-tk
  - sudo apt-get install python3-tk
install:
  - pip install -r requirements.txt # TODO conda
script:
  - pytest
